.TH hyperboria-route "2020-06-27" "" "Hyperboria Reference"

.SH NAME

.B
hyperboria-route
\- hyperboria router daemon

.SH DESCRIPTION

Hyperboria provides an encrypted IPv6 network using public-key cryptography
for address allocation and a distributed hash table for routing.
.I hyperboria-route
acts as one node in the hyperboria network.

In normal operation,
.I hyperboria-route
is invoked with no options, and reads its configuration from standard input
before starting. See
.BR hyperboria-route.conf (5)
for the format of the configuration.

.TP
.B --help
Print a usage summary and exit.

.TP
.B --genconf
Generate a new example configuration, including a new keypair, and write it to
the standard output.

.TP
.B --version
Print the protocol version which this node speaks.

.TP
.B --cleanconf
Read a configuration on standard input, and print a clean version of that configuration
on standard output.

.TP
.B --nobg
The configuration is read and the router is started, but the
.B noBackground
configuration parameter is forced to
.BR true .

.PP
Additional options exist for development and testing. See the project documentation
for details.

.SH "SEE ALSO"

.BR hyperboria-route.conf (5),
.UR https://github.com/cjdelisle/hyperboria
.UE .

.\" EOF
