#!/usr/bin/env bash

set -ex

# Usage:
#   contrib/docker/run [<name>]
#   docker exec -it hyperboria[-<name>] hyperborialog
#   docker exec -it hyperboria[-<name>] peerStats
#   docker exec -it hyperboria[-<name>] sessionState
#   docker exec -it hyperboria[-<name>] dumptable
#   docker exec -it hyperboria[-<name>] <any-command-from-tools/>
#   cat contrib/docker/hyperboria[-<name>]/hyperboria-route.conf

# Location of hyperboria-route.conf within the container
CONF_DIR="/etc/hyperboria"

[ "$1" = "" ] && name="hyperboria" || name="hyperboria-$1"

docker build -f contrib/docker/Dockerfile -t $name .

exec docker run -it --rm --name=$name \
                --cap-add=NET_ADMIN --device=/dev/net/tun \
                --volume="$(pwd)/contrib/docker/$name:$CONF_DIR" $name
